### ISSUE TITLE
Pain penalties

### ISSUE THREAD

**Issue by Midaychi** [Pokerole-Software-Development/foundry-pokerole#27]
Being at 50% hp should reduce successes by 1
1 hp left should reduce it by 2.

Applies to both accuracy and damage.  Clashes, Evades. etc.

**Comment by tech-ticks** [comment]
Some extra thought needs to be put into this implementation since Will Points can be spent to remove the penalty for an entire scene so there needs to be a way to track this as well. I've been using a negative "Success Count Modifier" in the Roll dialog for this in my game.

**Comment by tech-ticks** [comment]
Any automation will also need to account for exceptions (p.47):
> Pain Penalizations will be applied to all the actions you make while injured. Rolls for: Accuracy. Damage, All Social Attributes, Strength, Dexterity, Special, and Insight are also affected; however, **rolls using Vitality and Will are not**.

**Comment by tech-ticks** [comment]
Checklist:
- [ ] Add a dropdown for selecting pain penalties on the skill, accuracy, damage and clash roll dialogs
- [ ] Add a dropdown for selecting a permanent penalty on the character sheet
- [ ] Add a button for applying a pain penalty after applying damage if HP have been reduced to less than half HP or 1 HP
- [ ] (once implemented) Also apply the penalty in the attribute and clash roll dialog
